<?php

/**
 * CronJobs
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class CronJobs extends Doctrine_Record
{

	public function setTableDefinition()
	{
		$this->setTableName('cron_jobs');

		$this->hasColumn('job_modules', 'string', 999, array(
			'type'    => 'string',
			'length'  => 999,
			'notnull' => true
		));
	}
}