<?php

/**
 * EmailTemplates
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class EmailTemplates extends Doctrine_Record
{

	public function setUp()
	{
		$this->hasMany('EmailTemplatesDescription as Description', array(
			'foreign' => 'email_templates_id',
			'local'   => 'template_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition()
	{
		$this->setTableName('email_templates');

		$this->hasColumn('template_id', 'integer', 4, array(
			'type'          => 'integer',
			'length'        => 4,
			'unsigned'      => 0,
			'primary'       => true,
			'autoincrement' => true,
		));

		$this->hasColumn('template_status', 'integer', 1, array(
			'type'     => 'integer',
			'length'   => 1,
			'unsigned' => 0,
			'default'  => '0'
		));

		$this->hasColumn('template_name', 'string', 255, array(
			'type'    => 'string',
			'length'  => 255,
			'notnull' => true
		));

		$this->hasColumn('template_settings', 'string', 999);

		$this->hasColumn('email_module', 'string', 64, array(
			'type'    => 'string',
			'length'  => 64,
			'notnull' => true
		));

		$this->hasColumn('email_module_event_key', 'string', 64, array(
			'type'    => 'string',
			'length'  => 64,
			'notnull' => true
		));
	}
}