<?php

/**
 * FormManager
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class FormManager extends Doctrine_Record {

	public function setUp(){
		parent::setUp();

		$this->hasMany('FormManagerFields', array(
			'local' => 'form_id',
			'foreign' => 'form_id'
		));
	}

	public function setTableDefinition(){
		$this->setTableName('form_manager');

		$this->hasColumn('form_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true,
		));

		$this->hasColumn('form_key', 'string', 32, array(
			'type' => 'string',
			'primary' => false,
			'notnull' => false,
			'autoincrement' => false,
		));
	}
}