<?php

/**
 * OrdersStatus
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class SystemStatuses extends Doctrine_Record {

	public function setUp(){
		parent::setUp();

		$this->hasMany('SystemStatusesDescription as Description', array(
			'local' => 'status_id',
			'foreign' => 'status_id',
			'cascade' => array('delete')
		));
	}

	public function setTableDefinition(){
		$this->setTableName('system_statuses');

		$this->hasColumn('status_id', 'integer', 4, array(
			'type' => 'integer',
			'length' => 4,
			'unsigned' => 0,
			'primary' => true,
			'autoincrement' => true,
		));

		$this->hasColumn('status_types', 'string', 999);
	}
}