<?php

/**
 * OrdersStatusDescription
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 6401 2009-09-24 16:12:04Z guilhermeblanco $
 */
class SystemStatusesDescription extends Doctrine_Record {

	public function setUp(){
		parent::setUp();

		$this->setAttribute(Doctrine_Core::ATTR_COLL_KEY, 'language_id');

		$this->hasOne('SystemStatuses', array(
			'local' => 'status_id',
			'foreign' => 'status_id'
		));
	}

	public function setTableDefinition(){
		$this->setTableName('system_statuses_description');

		$this->hasColumn('status_id', 'integer', 4);
		$this->hasColumn('language_id', 'integer', 4);
		$this->hasColumn('status_name', 'string', 64);
	}

	public function newLanguageProcess($fromLangId, $toLangId){
		$Qdescription = Doctrine_Query::create()
			->from('SystemStatusesDescription')
			->where('language_id = ?', (int) $fromLangId)
			->execute(array(), Doctrine_Core::HYDRATE_ARRAY);
		foreach($Qdescription as $Record){
			$toTranslate = array(
				'name' => $Record['status_name']
			);

			EventManager::notify('SystemStatusesDescriptionNewLanguageProcessBeforeTranslate', $toTranslate);

			$translated = sysLanguage::translateText($toTranslate, (int) $toLangId, (int) $fromLangId);

			$newDesc = new SystemStatusesDescription();
			$newDesc->status_id = $Record['status_id'];
			$newDesc->language_id = (int) $toLangId;
			$newDesc->status_name = $translated['name'];

			EventManager::notify('SystemStatusesDescriptionNewLanguageProcessBeforeSave', $newDesc);

			$newDesc->save();
		}
	}

	public function deleteLanguageProcess($langId){
		Doctrine_Query::create()
			->delete('SystemStatusesDescription')
			->where('language_id = ?', (int) $langId)
			->execute();
	}
}