<?php

/**
 * ProductsPurchaseTypesToStores
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 */
class ProductsPurchaseTypesToStores extends Doctrine_Record
{

	public function setUp() {
		parent::setUp();

		$this->setAttribute(Doctrine::ATTR_COLL_KEY, 'stores_id');
		$this->hasOne('ProductsPurchaseTypes', array(
				'local' => 'purchase_type_id',
				'foreign' => 'purchase_type_id'
			));

		$ProductsPurchaseTypes = Doctrine_Core::getTable('ProductsPurchaseTypes')->getRecordInstance();
		$ProductsPurchaseTypes->hasMany('ProductsPurchaseTypesToStores', array(
				'local' => 'purchase_type_id',
				'foreign' => 'purchase_type_id',
				'cascade' => array('delete')
			));
	}

	public function setTableDefinition() {
		$this->setTableName('products_purchase_types_to_stores');

		$this->hasColumn('purchase_type_id', 'integer', 4, array(
				'type' => 'integer',
				'length' => 4,
				'fixed' => false,
				'primary' => false,
				'default' => '0',
				'notnull' => true,
				'autoincrement' => false
			));
		$this->hasColumn('stores_id', 'integer', 4, array(
				'type' => 'integer',
				'length' => 4,
				'fixed' => false,
				'primary' => false,
				'default' => '0',
				'notnull' => true,
				'autoincrement' => false
			));
		$this->hasColumn('price', 'decimal', 15, array(
				'type' => 'decimal',
				'length' => 15,
				'unsigned' => 0,
				'primary' => false,
				'default' => null,
				'notnull' => false,
				'autoincrement' => false,
				'scale' => 4
			));
		$this->hasColumn('tax_class_id', 'integer', 4, array(
				'type' => 'integer',
				'length' => 4,
				'unsigned' => 0,
				'primary' => false,
				'default' => null,
				'notnull' => false,
				'autoincrement' => false
			));
	}
}
